project_id = "wfolueffkdzknuowwecf"

[functions.create-payment]
verify_jwt = false

[functions.verify-diploma]
verify_jwt = false

[functions.france-travail-offers]
verify_jwt = false

[functions.la-bonne-boite]
verify_jwt = false